### ISSUE TITLE
Mis-parsing requires clauses as generic arguments

### ISSUE THREAD

**Issue by parno** [jaybosamiya/verusfmt#19]
In this program:
```
verus! {

fn test()
    requires i < 0, len > 0,
{
}    

} // verus!
```
We parse the requires clause as the `path_expr` `i<0,len>` followed by the unexpected token `0`, rather than the intended meaning of two binary expressions, namely `i < 0` and `len > 0`.  I don't immediately see an easy fix.

**Comment by jaybosamiya** [comment]
The lack of backtracking is a bit surprising, in particular because Pest is _supposed_ to backtrack, and after backtracking, I believe it _should_ be able to find a correct parse for this.

Example of Pest grammar that correctly backtracks even at arbitrary depth (tested with `'a'*100 + 'c'`):
```
x = { t | u }
t = { ("a" ~ t) | "b" }
t = { ("a" ~ t) | "c" }
```

I wonder if there is some Pest feature being used along the way that is preventing the backtrack from happening. But yeah, I agree, I don't see an immediate easy fix.

Just for future reference though, a fairly trivial workaround if anyone hits the same issue is to add parentheses:
```rust
verus! {

fn test()
    requires (i < 0), len > 0,
{
}    

} // verus!
```
